// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace VisionAnalyzer
{
	public partial class CustomDialogController : NSView
	{
		public CustomDialogController(IntPtr handle) : base(handle)
		{
		}
	}
}
